# Generated by Django 4.2.5 on 2023-09-27 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(default='ShopName', max_length=200)),
                ('contact', models.CharField(default='', max_length=200)),
                ('brand', models.CharField(default='Brand name', max_length=200)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('size', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media/pooja_app/images/collections/')),
                ('catogory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shoe_app.category')),
            ],
        ),
    ]
