# Generated by Django 4.2.5 on 2023-09-27 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_app', '0002_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
