# Generated by Django 4.2.5 on 2023-09-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_app', '0005_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
    ]
