# Generated by Django 4.2.5 on 2023-09-28 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_app', '0006_remove_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=''),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoe_app.product')),
            ],
        ),
    ]
