# Generated by Django 4.2.5 on 2023-09-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_app', '0007_alter_product_quantity_alter_product_size_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=''),
        ),
    ]
