# Generated by Django 4.2.5 on 2023-09-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_app', '0008_alter_cart_quantity_alter_cart_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(null=True),
        ),
    ]
